using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace iRadio_Free.Model
{
    public enum Genre
    {
        jazz,
        top_40,
        country,
        blues,
        easy_listening,
        rock,
        classical,
        DigitStart80s,
        chillout,
        oldies,
        reggae,
        dance,
        ambient,
        trance,
        hip_hop,
        smooth_jazz,
        DigitStart70s,
        house,
        lounge,
        drum_and_bass,
        metal,
        meditation,
        techno,
        DigitStart60s,
        heavy_metal,
        soul,
        pop,
        DigitStart90s,
        psytrance,
        latin,
        funk,
        rap,
        rockabilly,
        DigitStart50s,
        minimal,
        bollywood,
        greek,
        comedy,
        hindi,
        alternative,
        reggaeton,
        new_age,
        salsa,
        bluegrass,
        edm,
        manele,
        swing,
        talk,
        japanese,
        dancehall,
        disco,
        electronic,
        classic_rock,
        chill,
        psychedelic,
        dubstep,
        dub,
        rnb,
        hardstyle,
        progressive,
        indie,
        goa,
        romantic,
        kizomba,
        eurodance,
        folk,
        hardcore,
        soundtracks,
        celtic,
        americana,
        electro,
        jungle,
        new_wave,
        opera,
        goth,
        punk,
        jewish,
        downtempo,
        garage,
        indian

    }
    public enum Mode
    {
        Favorites,
        FeaturedPopular,
        Genre,
        Keyword
    }
}
